version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    env_file: .env
    ports:
      - "$PORT:$PORT"
    develop:
      watch:
        - action: rebuild
          path: ./go.mod
        - action: rebuild
          path: ./go.sum
        - action: sync
          path: .
          target: /app
          ignore:
            - tmp/
            - .git/
            - .env
            - README.md
            - Dockerfile*
            - docker-compose.yaml